name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Create image java
        run: make build
      
      - name: Run the tests
        run: make test
